clusterName: hivewiki-dev

env:
  AWS_REGION: ap-northeast-2

tolerations:
  - operator: Exists
  - key: dedicated
    operator: Equal
    value: infra
    effect: NoSchedule
  - key: node.cilium.io/agent-not-ready
    operator: Equal
    value: "true"
    effect: NoExecute
