# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "hivewiki-infra-state-bucket"
    encrypt      = true
    key          = "live/cluster/observability/terraform.tfstate"
    region       = "ap-northeast-2"
    use_lockfile = true
  }
}
