name: OpenTofu Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - ".terraform.lock.hcl"

jobs:
  plan:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        working_directory:
          - environments/dev
          - environments/prod
          - environments/shared

    defaults:
      run:
        working-directory: ${{ matrix.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # 5.0.1

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu init
        run: tofu init -backend=false -input=false

      - name: OpenTofu plan
        run: tofu plan -no-color -input=false
